version: '3.4'

services:
  catelogdb:
    container_name: catelogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  #basketdb:
  #  container_name: basketdb
  #  restart: always
  #  ports:
  #    - "6379:6379"

  #orderdb:
  #  container_name: orderdb
  #  environment:
  #    - ACCEPT_EULA="Y"
  #    - SA_PASSWORD="1StrongPwd!!"
  #  restart: always
  #  ports:
  #    - "1435:1433"
  
  #pgadmin:
  #  container_name: pgadmin
  #  environment:
  #    - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
  #    - PGADMIN_DEFAULT_PASSWORD=admin1234
  #  restart: always
  #  ports:
  #    - "5050:80"
  #  volumes:
  #    - pgadmin_data:/root/.pgadmin
  
  #discountdb:
  #  container_name: discountdb
  #  environment:
  #    - POSTGRES_USER=admin
  #    - POSTGRES_PASSWORD=admin1234
  #    - POSTGRES_DB=DisountDb
  #  restart: always
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catelog.api:
    container_name: catelog.api
    environment:
      - "DatabaseSettings:ConnectionString=mongodb://catelogdb:27017"
      - "ApiSettings:ZipkinUrl=http://zipkin:9411/api/v2/spans"
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - catelogdb
    ports:
      - "8000:80"

  #basket.api:
  #  container_name: basket.api
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "CacheSettings:ConnectionString=basketdb:6379"
  #    - "GrpcSettings:DiscountUri=http://discount.grpc"
  #    - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
  #  depends_on:
  #    - basketdb
  #    - rabbitmq
  #  ports:
  #    - "8001:80"


  #discount.api:
  #  container_name: discount.api
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "DatabaseSettings:ConnectionString=Server=DiscountDb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
  #  depends_on:
  #    - discountdb
  #  ports:
  #    - "8002:80"


  #discount.grpc:
  #  container_name: discount.grpc
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "DatabaseSettings:ConnectionString=Server=DiscountDb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
  #  depends_on:
  #    - discountdb
  #  ports:
  #    - "8003:80"

  #rabbitmq:
  #  container_name: rabbitmq
  #  restart: always
  #  ports:
  #    - "5672:5672"
  #    - "15672:15672"

  #ordering.api:
  #  container_name: ordering.api
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "ConnectionStrings:OrderingConnectionString=Server=localhost;Database=OrderDb;User Id=testuser;Password=testuser@123;MultipleActiveResultSets=true;"
  #    - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
  #  depends_on:
  #    - rabbitmq
  #  ports:
  #    - "8004:80"


  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - catelog.api
        #- basket.api
        #- discount.api
        #- ordering.api
    ports:
      - "8010:80"


  #shopping.aggregator:
  #  container_name:  shopping.aggregator
  #  depends_on:
  #    - catelog.api
  #    - basket.api
  #    - ordering.api
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "ApiSettings:CatalogUrl=http://catalog.api"
  #    - "ApiSettings:BasketUrl=http://basket.api"
  #    - "ApiSettings:OrderingUrl=http://ordering.api"
  #  ports:
  #    - "8005:80"


  aspnetrunbasics:
    container_name: aspnetrunbasics
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:GatewayAddress=http://ocelotapigw"
      - "ApiSettings:ZikinUrl=http://zipkin/api/v2/spans"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      #- ocelotapigw
      - catelog.api
      #- basket.api
      #- discount.api
      #- ordering.api
    ports:
      - "8006:80"

  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601" 
  
  zipkin:
    container_name: zipkin
    ports:
      - "9411:9411"
      
  webstatus:
    container_name: webstatus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=Catalog Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://catelog.api/hc
      - HealthChecksUI__HealthChecks__1__Name=Basket Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://basket.api/hc
      - HealthChecksUI__HealthChecks__2__Name=Discount Health Check
      - HealthChecksUI__HealthChecks__2__Uri=http://discount.api/hc
      - HealthChecksUI__HealthChecks__3__Name=Ordering Health Check
      - HealthChecksUI__HealthChecks__3__Uri=http://ordering.api/hc
      - HealthChecksUI__HealthChecks__4__Name=Shopping Aggregator Health Check
      - HealthChecksUI__HealthChecks__4__Uri=http://shopping.aggregator/hc
      - HealthChecksUI__HealthChecks__5__Name=AspnetRunBasics WebMVC Health Check
      - HealthChecksUI__HealthChecks__5__Uri=http://aspnetrunbasics/hc
    ports:
      - "8007:80"

